image: atlassianlabs/docker-node-jdk-chrome-firefox
pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - npm install
          - npm run-script build
          # - npm test